### ISSUE TITLE
Use BerkelyDB 5.5

### ISSUE THREAD

**Issue by BastelPichi** [aaronmidnight/magi-utilities#1]
While BerkelyDB 5.5 isn't downwards compatible, for better performance and security, version 5.5 should be used.

The PeerCoin repo claims that the 4.8 is required, however the magi source claims that 5.5 works fine as well.
https://github.com/m-pays/magi/blob/master/doc/readme-qt.rst
However PeerCoin also claims that BerkelyDB isnt completely optional. This could however be false as magi runs of a significantly lower version of ppcoin source.

Have you ever tried without or using BerkelyDB5.5?

**Comment by aaronmidnight** [comment]
Hey BastelPichi

Interesting thought. No, I've never tried DB 5.5 before but I tried to compile magid without any DB installed. Sadly it didn't work for me, because 3n37 once said that it worked for him. You can ask him about this. 
Could you send a link to download db 5.5? I could make some testing then.

**Comment by BastelPichi** [comment]
You can apprently find anything up to 5.3 on the web. Im busy with other stuff, so closing for now.
